import { ColumnDef } from '@tanstack/react-table';
import {
  bidBrokerCol,
  bidCpCol,
  bondCodeCol,
  bondRatingCol,
  commentCol,
  csiCleanPriceCol,
  csiFullPriceCol,
  csiYieldCol,
  dealTimeCol,
  deliveryDateCol,
  firstMaturityDateCol,
  impliedRatingCol,
  issuerRatingCol,
  liquidationSpeedCol,
  listedDateCol,
  ofrBrokerCol,
  ofrCpCol,
  operatorCol,
  optionTypeCol,
  pvbpCol,
  pxCol,
  repaymentMethodCol,
  shortNameCol,
  tradedDateCol,
  valCleanPriceCol,
  valModifiedDurationCol,
  valYieldCol,
  volCol
} from '@/pages/ProductPanel/components/DealTable/columns';
import { DealTableColumn } from '@/pages/ProductPanel/components/DealTable/types';

export const columns: ColumnDef<DealTableColumn>[] = [
  dealTimeCol,
  pxCol,
  volCol,
  ofrCpCol,
  bidCpCol,
  ofrBrokerCol,
  bidBrokerCol,
  optionTypeCol,
  listedDateCol,
  repaymentMethodCol,
  valModifiedDurationCol,
  operatorCol,
  commentCol,
  firstMaturityDateCol,
  bondCodeCol,
  shortNameCol,
  issuerRatingCol,
  tradedDateCol,
  deliveryDateCol,
  bondRatingCol,
  valCleanPriceCol,
  valYieldCol,
  csiCleanPriceCol,
  csiFullPriceCol,
  csiYieldCol,
  liquidationSpeedCol,
  impliedRatingCol,
  pvbpCol
];
