export const RECEIPT_DEAL_LOG_TABLE_PAGE_SIZE = 50;
export const RECEIPT_DEAL_LOG_TABLE_MAX_PAGE = 10;
export const RECEIPT_DEAL_LOG_TABLE_MAX_SIZE = RECEIPT_DEAL_LOG_TABLE_PAGE_SIZE * RECEIPT_DEAL_LOG_TABLE_MAX_PAGE;
